### ISSUE TITLE
REST API question

### ISSUE THREAD

**Issue by chrissbarnett** [geoblacklight/geomonitor#24]
Hi guys...great app! Do you guys have any docs for the RESTful API? Specifically, I'd like to get a feed of services that are failing for us for a given host. 

Most of our failing layers on the public server are performance problems, so it would help to know which layers need a little extra love! (maybe pregeneralized features?)

**Comment by mejackreed** [comment]
@chrissbarnett we are currently doing a little TLC on GeoMonitor to integrate with GeoBlacklight. This is something that we can add in without to much of a headache.
