### ISSUE TITLE
Verify layer's existence in Solr index before checking layer

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geomonitor#51]
This layer is still being monitored actively:

  https://geomonitor.stanford.edu/layers/stanford-gy826dj4762

despite having been removed from the Solr index in the geoblacklight installation:

  https://earthworks.stanford.edu/catalog/stanford-gy826dj4762.json

**Comment by mejackreed** [comment]
We need to add a scheduled task for `rake solr:deactivate` here: https://github.com/geoblacklight/geomonitor/blob/master/config/schedule.rb
